name: Clean Old Package Images
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily
jobs:
  cleanup:
    runs-on: self-hosted
    steps:
      - name: Delete old package versions
        uses: actions/delete-package-versions@v4
        with:
          owner: 'Jolymmiets'
          package-name: 'remnawave-telegram-shop-bot-fce08bf'
          package-type: 'container'
          min-versions-to-keep: 5
          token: ${{ secrets.GITHUB_TOKEN }}